version: '2'
services:
    aviva-app:
        image: aviva
        external_links:
            - aviva-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/aviva?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8008:8008
    aviva-mysql:
        extends:
            file: mysql.yml
            service: aviva-mysql
